---
global:
  provider: local
  env: dev
  network: mainnet

elc:
  storage:
    size: "5Gi"
  tolerations: []
  affinity: {}
  service:
    monitor:
      podTargetLabels:
        - "ethereum/elc"
        - "ethereum/elc_version"
        - "ethereum/clc"
        - "ethereum/clc_version"
        - "ethereum/network"
        - "ethereum/owner"
        - "ethereum/env"

clc:
  storage:
    size: "5Gi"
  tolerations: []
  affinity: {}
  service:
    monitor:
      podTargetLabels:
        - "ethereum/elc"
        - "ethereum/elc_version"
        - "ethereum/clc"
        - "ethereum/clc_version"
        - "ethereum/network"
        - "ethereum/owner"
        - "ethereum/env"
