---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "ethnode-clc.resourceName" . }}
  namespace: {{ include "ethnode.namespace" . }}
  labels:
    {{- include "ethnode-clc.labels" $ | nindent 4 }}
    {{- with .Values.service.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.service }}
  {{- if .annotations }}
  annotations:
    {{- toYaml .annotations | nindent 6 }}
  {{- end }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "ethnode-clc.selectorLabels" . | nindent 4 }}
  {{- with .Values.service }}
  ports:
    {{- toYaml .ports | nindent 4 }}
  {{- end }}

---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "ethnode-clc.resourceName" . }}-servicemonitor
  namespace: {{ include "ethnode.namespace" . }}
  labels:
    {{- include "ethnode-clc.labels" $ | nindent 4 }}
    {{- with .Values.service.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  namespaceSelector:
    matchNames:
    - {{ include "ethnode.namespace" . }}
  selector:
    matchLabels:  
    {{- include "ethnode-clc.selectorLabels" . | nindent 6 }}      
  endpoints:
  - port: clc-metrics
    interval: 15s
    path: /metrics
    scheme: http
    honorLabels: true
    relabelings:
      - sourceLabels: [__meta_kubernetes_pod_label_ethereum_clc, __meta_kubernetes_pod_label_ethereum_clc_version]
        separator: ":"
        targetLabel: cl_client
        replacement: "$1:"
      - sourceLabels: [__meta_kubernetes_pod_label_ethereum_network]
        targetLabel: network
      - sourceLabels: [__meta_kubernetes_pod_label_ethereum_owner]
        targetLabel: owner
      - sourceLabels: [__meta_kubernetes_pod_label_ethereum_env]
        targetLabel: env
      - sourceLabels: [__meta_kubernetes_pod_label_vpc]
        regex: "(.+)"
        targetLabel: vpc
      - sourceLabels: [__meta_kubernetes_pod_label_vnet]
        regex: "(.+)"
        targetLabel: vnet
      - sourceLabels: [__meta_kubernetes_service_name]
        targetLabel: instance
      - action: labeldrop
        regex: job
    {{- with .Values.service.monitor }}
    {{- if .relabelings }}
    {{- toYaml .relabelings | nindent 4 }}
    {{- end }}
    {{- end }}
  {{- with .Values.service.monitor }}
  {{- if and (.podTargetLabels) (eq (kindOf .podTargetLabels) "slice" ) }}
  podTargetLabels: {{ .podTargetLabels }}
  {{- end }}
  {{- end }}
